default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV["DB_POOL"] || ENV["RAILS_MAX_THREADS"] || 5 %>
  url: <%= ENV["DATABASE_URL"] %>

production:
  <<: *default
development:
  <<: *default
test:
  <<: *default
